AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable

Style/FrozenStringLiteralComment:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Layout/IndentationWidth:
  Width: 4

Style/MultilineBlockChain:
  Enabled: false
